version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - MONGODB_URL=mongodb://mongodb_container:27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
    depends_on:
      - mongodb_container
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "start:dev"]

volumes:
  mongodb_data_container:
