services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./books.json:/docker-entrypoint-initdb.d/books.json

  redis_container:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    environment:
      MONGO_URL: mongodb://root:password@mongodb_container:27017/
      REDIS_URL: redis://redis_container:6379
    depends_on:
      - mongodb_container
      - redis_container

volumes:
  mongodb_data_container:
